### ISSUE TITLE
schematic as PDF

### ISSUE THREAD

**Issue by urs8000** [ttnmapper/ttntrackernode#1]
hi
not all are using KiCad,so it would be very friendly if you could add a PDF printout of the schematic and the board.

additionally I suggest using an atmega1284p with more memory and hardware serial.
I added an OpenLog board for logging each send, to disguinguish between received and lost packages (red / green dotted map)
https://github.com/urs8000/LoRa-Gateway-Locator

**Comment by jpmeijers** [comment]
The design is still a work in progress, so creating a PDF of the schematic now is a bit premature.

Using a more expensive ATmega1284p is overkill as we make use of the RN2483 and therefore do not need the extra memory (as we don't use the LMIC stack). The 32u4 has native USB, giving you a "hardware" serial to the computer. That leaves the hardware serial port open for use with the RN2483.

Another reason for using the ATmega32u4 is compatibility with the Things Uno and Things Node. This way you can use The Things Network libraries on this device without any changes.

**Comment by TD-er** [comment]
Well, it doesn't look like there has been a lot of recent activity on the PCB, so I would not mind having a schematic in either PNG or PDF.
Now I have to install KiCad to look at the schematics.
