### ISSUE TITLE
LEDs

### ISSUE THREAD

**Issue by dbrgn** [ttnmapper/ttntrackernode#3]
I'm not sure if I missed it in the schematics, but some more status LEDs would be useful:

- LoRaWAN join state (for OTAA)
- When data is sent over LoRaWAN (could be combined with join state)
- GPS fix (an RGB LED or just a yellow and a green LED to indicate accuracy would be awesome)

**Comment by KolijnWolfaardt** [comment]
Hi @dbrgn, thanks for the suggestion, it will definitely help make the software state of the tracker more visible. Do you know of a specific LED you'd like to suggest, and would you like to implement it?

**Comment by dbrgn** [comment]
No, I was thinking of generic 0805 SMD LEDs, unless you want to use a WS2812b RGB LED aka Neopixel. But labelled single LEDs are easier to understand than memorizing color codes :)

> would you like to implement it

Not this week, but maybe later (unless you want to do it yourself). Where do you usually get your parts, Digikey? (I think it's important that all parts in KiCad have an order number in the metadata.)

**Comment by KolijnWolfaardt** [comment]
Commit 4d2b95 adds an WS2812b led.
