### ISSUE TITLE
Clarifications needed

### ISSUE THREAD

**Issue by catalinalb** [ttnmapper/ttntrackernode#7]
Hello,

Would like to flash my TTGO T-beam (with OLED) with TTN Tracker. 
Unfortunatly I don´t really understand for what boards it can be used.
Can someone add some clairfications or help me out?

Thank you

**Comment by jpmeijers** [comment]
Have a look at https://github.com/ttnmapper/gps-node-examples to find example for different devices.

This repo is a specific device and won't work on different hardware.
